Repository AY2223S2-CS2103T-F12-4/tp, pull requests merged in 2023-03, with the labels that each got.

#3 Add new remark command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#64 Duplicate person models and modify to fit new opening model
  src/main/java/seedu/address/model/opening/Company.java
  src/main/java/seedu/address/model/opening/Contact.java
  src/main/java/seedu/address/model/opening/Date.java
  src/main/java/seedu/address/model/opening/Opening.java
  src/main/java/seedu/address/model/opening/Position.java
  src/main/java/seedu/address/model/opening/Status.java
Labels: type.Task, priority.High

#71 Update model and change contact references to email
  src/main/java/seedu/address/model/ModelManagerNew.java
  src/main/java/seedu/address/model/ModelNew.java
  src/main/java/seedu/address/model/ReadOnlyUltron.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefsNew.java
  src/main/java/seedu/address/model/Ultron.java
  src/main/java/seedu/address/model/UserPrefsNew.java
  src/main/java/seedu/address/model/opening/Email.java
  src/main/java/seedu/address/model/opening/Opening.java
  src/main/java/seedu/address/model/opening/Status.java
  src/main/java/seedu/address/model/opening/UniqueOpeningList.java
  src/main/java/seedu/address/model/opening/exceptions/DuplicateOpeningException.java
  src/main/java/seedu/address/model/opening/exceptions/OpeningNotFoundException.java
Labels: type.Task, priority.High

#74 Add new edit command
  src/main/java/seedu/address/logic/commands/EditCommandNew.java
  src/main/java/seedu/address/model/ModelManagerNew.java
  src/main/java/seedu/address/model/ModelNew.java
Labels: type.Task, priority.High

#75 Update UG
  docs/UserGuide.md
Labels: priority.High

#77 Add new edit parser
  src/main/java/seedu/address/logic/commands/AddCommandNew.java
  src/main/java/seedu/address/logic/commands/EditCommandNew.java
  src/main/java/seedu/address/logic/parser/AddCommandParserNew.java
  src/main/java/seedu/address/logic/parser/CliSyntaxNew.java
  src/main/java/seedu/address/logic/parser/EditCommandParserNew.java
Labels: priority.High

#79 Refactor all command/parser logic and main logic
  src/main/java/seedu/address/logic/commands/ClearCommandNew.java
  src/main/java/seedu/address/logic/commands/DeleteCommandNew.java
  src/main/java/seedu/address/logic/commands/ExitCommandNew.java
  src/main/java/seedu/address/logic/commands/FindCommandNew.java
  src/main/java/seedu/address/logic/commands/HelpCommandNew.java
  src/main/java/seedu/address/logic/commands/ListCommandNew.java
  src/main/java/seedu/address/logic/commands/RemarkCommandNew.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParserNew.java
  src/main/java/seedu/address/logic/parser/FindCommandParserNew.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParserNew.java
  src/main/java/seedu/address/logic/parser/UltronParser.java
Labels: type.Task, priority.High

#83 Edited Sample Data
  src/main/java/seedu/address/model/util/SampleDataUtilNew.java
Labels: priority.High

#105 Add status command to UG
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#109 Add status command
  src/main/java/seedu/ultron/logic/commands/FindCommand.java
  src/main/java/seedu/ultron/logic/commands/StatusCommand.java
  src/main/java/seedu/ultron/model/opening/StatusContainsKeywordPredicate.java
Labels: priority.High

#125 Refactor common and util files to make them ready for use in testing
  src/main/java/seedu/ultron/commons/util/JsonUtil.java
  src/main/java/seedu/ultron/model/util/SampleDataUtil.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/commons/util/CollectionUtilTest.java
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/Assert.java
  src/test/java/seedu/address/testutil/EditOpeningDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OpeningBuilder.java
  src/test/java/seedu/address/testutil/OpeningUtil.java
  src/test/java/seedu/address/testutil/SerializableTestClass.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexesNew.java
  src/test/java/seedu/address/testutil/TypicalOpenings.java
  src/test/java/seedu/address/testutil/UltronBuilder.java
Labels: type.Task

#118 Added upcoming command
  src/main/java/seedu/ultron/logic/commands/UpcomingCommand.java
  src/main/java/seedu/ultron/logic/parser/ParserUtil.java
  src/main/java/seedu/ultron/logic/parser/UltronParser.java
  src/main/java/seedu/ultron/logic/parser/UpcomingCommandParser.java
  src/main/java/seedu/ultron/model/opening/OpeningsBeforeDaysPredicate.java
Labels: priority.High

#133 fix delete command.
  src/main/java/seedu/ultron/logic/commands/DeleteCommand.java
  src/main/java/seedu/ultron/model/Model.java
  src/main/java/seedu/ultron/model/ModelManager.java
Labels: type.Bug, severity.High

#142 Result display and success messages improvement
  src/main/java/seedu/ultron/model/opening/Opening.java
  src/main/java/seedu/ultron/ui/OpeningDetailsPanel.java
  src/main/java/seedu/ultron/ui/ResultDisplay.java
  src/main/resources/view/UIUpgrade.css
Labels: type.Enhancement

#145 Update messages
  src/main/java/seedu/ultron/logic/commands/AddCommand.java
  src/main/java/seedu/ultron/logic/commands/DeleteCommand.java
  src/main/java/seedu/ultron/logic/commands/EditCommand.java
  src/main/java/seedu/ultron/logic/commands/FindCommand.java
  src/main/java/seedu/ultron/logic/commands/ListCommand.java
  src/main/java/seedu/ultron/logic/commands/RemarkCommand.java
  src/main/java/seedu/ultron/logic/commands/SortCommand.java
  src/main/java/seedu/ultron/logic/parser/SortCommandParser.java
  src/main/java/seedu/ultron/logic/parser/UltronParser.java
  src/main/java/seedu/ultron/model/opening/Keydate.java
  src/main/java/seedu/ultron/model/opening/Position.java
  src/main/java/seedu/ultron/model/opening/Remark.java
  src/main/java/seedu/ultron/model/opening/Status.java
  src/test/java/seedu/address/model/opening/PositionTest.java
Labels: priority.Medium

#149 Update message
  src/main/java/seedu/ultron/logic/commands/FindCommand.java
  src/main/java/seedu/ultron/logic/commands/RemarkCommand.java
  src/main/java/seedu/ultron/logic/commands/ShowCommand.java
  src/main/java/seedu/ultron/logic/commands/StatusCommand.java
  src/main/java/seedu/ultron/logic/commands/UpcomingCommand.java
Labels: priority.Medium

#150 User guide
  docs/UserGuide.md
  docs/images/Add.png
  docs/images/Delete.png
  docs/images/Edit.png
  docs/images/Find.png
  docs/images/List.png
  docs/images/Remark.png
  docs/images/Status.png
  docs/images/Ui.png
  docs/images/Upcoming.png
Labels: priority.High

#151 Finalise 1.3 ug
  docs/UserGuide.md
  src/main/java/seedu/ultron/logic/commands/RemarkCommand.java
Labels: priority.Medium
